### ISSUE TITLE
Modelos de la base de datos

### ISSUE THREAD

**Issue by RoiMP** [AulaEstudio-Team/AE-Games#12]
# Añadir los modelos de la base de datos
**Modelo de minijuego**
- Creador
- Nombre
- URL
- Portada

**Modelo de usuario**
- Nickname
- eMail
- Fecha de ingreso
- Última conexión
- Logros
- Experiencia
- Avatar

**Modelo de puntuación**
- Minijuego
- Usuario
- Puntuación

**Modelo de Creador**
- Nombre
- URL
- Imagen
- Descripción

**Modelo de victorias derrotas**
- Minijuego
- Usuario
- Victorias
- Derrotas

**Modelo de Logro**
- Minijuego
- Nombre
- Medalla

**Comment by CarlosSoto03** [comment]
Podrías añadir los github de los creadores en la base de datos.
