### ISSUE TITLE
Crear páginas de registro y de login

### ISSUE THREAD

**Issue by CarlosSoto03** [AulaEstudio-Team/AE-Games#34]
Creción de páginas de Registro y Login
## Registro
- Username
- Correo electrónico
- Doble password

### Inicio de Sesion
- Username
- Password

**Comment by RoiMP** [comment]
Podéis usar los forms de Django para ahorraros trabajo: https://docs.djangoproject.com/en/4.1/topics/auth/default/#django.contrib.auth.views.LoginView
