### ISSUE TITLE
[MINIGAME] 4 en Raya

### ISSUE THREAD

**Issue by IvanPeM** [AulaEstudio-Team/AE-Games#4]
# 4 en Raya
Juego de hacer una línea de 4 fichas del mismo color.

### Básicas
- [x] El usuario hace clic y coloca la ficha
- [x] La ficha colocada baja hasta el fondo de todo.

### Avanzado
- [x] Compruebe si la ficha está en línea.
- [x] Pantalla de ganador.
- [x] Marcador de resultados.
- [x] IA que coloca fichas aleatorias.
- [ ] IA básica para el enemigo.
- [ ] Ranking de jugadores.
- [ ] Logros

**Comment by IvanPeM** [comment]
Ya arreglé el tema de poner muchas fichas a la vez. 
Estoy pensando en poner un marcador para saber quien va ganado si la IA o tu mismo.

**Comment by RoiMP** [comment]
Pues es buena idea, que vaya guardando cuantas victorias y derrotas llevas. Impleméntalo en js y después vemos como podemos hacer para que se utilice Django para guardar estos valores. Y así si yo me salgo de la página y entro en otro navegador con mi cuenta, me recuerde las victorias y derrotas que llevo. 

El leaderboard será un recuento de la persona que más victorias tenga

**Comment by RoiMP** [comment]
Si puedes añade al issue en el checklist de avanzado: 

- [ ] IA básica para el enemigo
- [ ] Marcador de resultados
- [ ] Ranking de jugadores (más victorias y mejor ratio victorias derrotas)
- [ ] Logros 

Ideas para logros: Detectar cuando se lleven 1/5/10 victorias, 1 derrota, llenar un 50% del tablero, conseguir un empate, ganar con una línea vertical/horizontal/diagonal, ganar con dos líneas a la vez, conectarse por X vez, descubrir algún secreto...

**Comment by carlosgamallo** [comment]
Hola Ivan, me gusta mucho tu idea. En tu juego habrá un timer para saber cuanto tiempo me lleva ganar una partida?

**Comment by IvanPeM** [comment]
> Hola Ivan, me gusta mucho tu idea. En tu juego habrá un timer para saber cuanto tiempo me lleva ganar una partida?

Hola carlosgamallo, muchas gracias por tu aporte ya que no sabía cuanta experiencia ponerle a cada partida ganada.😀
