### ISSUE TITLE
[MINIGAME] WORDLE

### ISSUE THREAD

**Issue by MarcoteRL** [AulaEstudio-Team/AE-Games#7]
# Wordle
El minijuego consiste en adivinar una palabra aleatoria de 5 letras. Dependiendo de las letras introducidas el juego mostrará que
la letra existe, existe pero está en otra posición o no se encuentra la letra en la palabra aleatoria.

### Básico
- [X] Se comprueba que la palabra introducida es igual a la aleatoria.
- [ ] El usuario puede hacer click en una posición de la palabra para introducir la letra.
- [ ] Detectar el input del usuario. ( Introducir letras, borrar, presionar Enter, Espacio para cambiar de posición.. )
- [ ] Se verifican las letras y cambia el fondo de las mismas (correcto, posición incorrecta, no encontrada).

### Avanzado
- [ ] La palabra introducida se comprueba en un diccionario para ver si existe.

## Futuro diseño
![Wordle](https://compote.slate.com/images/a528b23d-2dad-44d9-b8d0-4e92167bb165.png?crop=1560%2C1040%2Cx0%2Cy0)

**Comment by IvanPeM** [comment]
1. Como harás para pulsar en una posición en cada palabra.

**Comment by MarcoteRL** [comment]
> 1. Como harás para pulsar en una posición en cada palabra.

Donde se introducen las letras es una tabla con tds, estas casillas tienen un id que contienen el col y row (id = ${col}${row}). De esa manera, cuando se haga un click en una casilla, recogeré el id para saber la posición y trabajar con esa letra.
Solo se podrá pulsar en la fila que toque, dependiendo de los intentos que lleve el usuario.
